name:                regex-logic
version:             0.1.0.1
homepage:            https://github.com/sordina/regex-logic#readme
license:             BSD3
author:              Lyndon
maintainer:          maydwell@gmail.com
copyright:           2018 Lyndon Maydwell
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - megaparsec
  - logict
  - template-haskell
  - algebraic-graphs
  - mtl

library:
  source-dirs:      src
  exposed-modules:
    - Data
    - Regex
    - Match
    - Generate
    - Parse
    - RegexQQ

executables:
  regex-logic:
    source-dirs:      src
    main:             Main.hs
